### ISSUE TITLE
Incorret paramater indentation with align_parameter + chop_down_parameter

### ISSUE THREAD

**Issue by Lexicality** [Koihik/LuaFormatter#156]
Using latest version of vscode extension

Config
```yaml
align_parameter: false
chop_down_parameter: true
break_after_functiondef_lp: true
```
Input:
```lua
local function foo(one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen)
    return 5
end
```
expected
```lua
local function foo(
    one,
    two,
    three,
    four,
    five,
    six,
    seven,
    eight,
    nine,
    ten,
    eleven,
    twelve,
    thirteen
) return 5 end
```
actual
```lua
local function foo(
    one,
    two,
        three,
        four,
        five,
        six,
        seven,
        eight,
        nine,
        ten,
        eleven,
        twelve,
        thirteen
) return 5 end
```
Seems to be caused by `align_parameter: false`, setting `align_parameter: true` works

Additional bug caused by `continuation_indent_width: 1`:
```yaml
use_tab: true
continuation_indent_width: 1
align_parameter: false
chop_down_parameter: true
break_after_functiondef_lp: true

```
output
```lua
local function foo(
	one,
two,
		three,
		four,
		five,
		six,
		seven,
		eight,
		nine,
		ten,
		eleven,
		twelve,
		thirteen) return 5 end
```
