### ISSUE TITLE
Break after/before in functioncall does not take column_limit into consideration

### ISSUE THREAD

**Issue by Yamsha75** [Koihik/LuaFormatter#162]
Function calls are split into lines regardless of `column_limit` setting:

Configuration:
```yml
column_limit: 88
break_after_functioncall_lp: true
break_before_functioncall_rp: true
```
Example:
```lua
-- before formatting
addEvent("onPlayerJoin", true)

-- after formatting
addEvent(
        "onPlayerJoin", true
)

-- expected, because the line isn't long enough
addEvent("onPlayerJoin", true)
```

Similar parameters for function definitions do behave differently, as they take `column_limit` into account.

Configuration:
```yml
column_limit: 88
break_after_functiondef_lp: true
break_before_functiondef_rp: true
```

Example:
```lua
-- before formatting
function example_function(parameter1, parameter2)
    return true
end

function example_of_a_very_long_function_name(parameter1, parameter2, parameter3, parameter4)
    return true
end

-- after formatting
function example_function(parameter1, parameter2)
    return true
end

function example_of_a_very_long_function_name(
        parameter1, parameter2, parameter3, parameter4
)
    return true
end
```
