### ISSUE TITLE
Tabs after spaces when function arguments split

### ISSUE THREAD

**Issue by Zash** [Koihik/LuaFormatter#168]
When long function arguments are split across many lines and tabs are used, the split lines have spaces before tabs. I would expect tabs to get to the right indentation level, followed by spaces for alignment.

## Config

```yaml
align_args: true
align_parameter: false
align_table_field: true
break_after_functioncall_lp: false
break_after_functiondef_lp: false
break_after_operator: false
break_after_table_lb: true
break_before_functioncall_rp: false
break_before_functiondef_rp: false
break_before_table_rb: true
chop_down_kv_table: true
chop_down_parameter: false
chop_down_table: true
column_limit: 100
column_table_limit: 100
continuation_indent_width: 1
double_quote_to_single_quote: false
extra_sep_at_table_end: true
indent_width: 1
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
single_quote_to_double_quote: true
spaces_before_call: 1
table_sep: ";"
tab_width: 1
use_tab: true
```

## Input

```lua
do
do
do
foobar()
function_with_oh_so_very_long_name("argument", "another argument that is quite long", "yet another long string argument")
barfoo()
end
end
end
```

## Expected Output

Tabs replaced by `→` for visibility.

```lua
do
 →do
 → →do
 → → →foobar()
 → → →function_with_oh_so_very_long_name("argument", "another argument that is quite long",
 → → →                                   "yet another long string argument")
 → → →barfoo()
 → →end
 →end
end
```

## Actual output

```lua
do
 →do
 → →do
 → → →foobar()
 → → →function_with_oh_so_very_long_name("argument", "another argument that is quite long",
                                    → → →"yet another long string argument")
 → → →barfoo()
 → →end
 →end
end
```
