### ISSUE TITLE
[Question] Which LuaFormatter option to change?

### ISSUE THREAD

**Issue by TornaxO7** [Koihik/LuaFormatter#241]
Hello! First of all, thank you for this project!

I've this `/tmp/test.lua` file:

<details>

```lua
ls.snippets.text = {s("trigger", {t("Wow! Text!")})}
```

</details>

And this is in my `~/.config/luaformatter/config.yaml`:

<details>

```yaml
keep_simple_control_block_one_line: false
keep_simple_block_one_line: false
break_after_operator: false
chop_down_table: true
chop_down_kv_table: true
```

</details>

What do I have to change to get the table as follows?

<details>

```lua
ls.snippets.text = {
    s("trigger", {
        t("Wow! Text!")
    })
}
```

</details>

**Comment by lmburns** [comment]
I set my configuration to this and it did what you want

```yaml
column_limit: 90
indent_width: 2
use_tab: false
tab_width: 4
continuation_indent_width: 4
keep_simple_control_block_one_line: false
keep_simple_function_one_line: false
align_args: true
align_parameter: false
align_table_field: true
spaces_before_call: 1
spaces_inside_functioncall_parens: false
spaces_inside_functiondef_parens: false
spaces_inside_table_braces: true
spaces_around_equals_in_field: true
chop_down_parameter: true
chop_down_table: true
chop_down_kv_table: true
break_after_functioncall_lp: false
break_before_functioncall_rp: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
break_after_table_lb: true
break_before_table_rb: true
break_after_operator: true
table_sep: ","
extra_sep_at_table_end: true
double_quote_to_single_quote: false
single_quote_to_double_quote: true
line_breaks_after_function_body: 1

column_table_limit: 20
line_separator: lf
```

The main thing here to note is the `column_table_limit` and `break_after_table_lb`
