### ISSUE TITLE
Configuration option "column_limit" ignored

### ISSUE THREAD

**Issue by kaklakariada** [Koihik/LuaFormatter#245]
lua-format seems to ignore the "column_limit" option. I set `column_limit: 120` in `.lua-format` but the line with 134 chars in the following example is not broken into multiple lines as I would have expected:

```lua
local function dummy()
    if num_results == 0 then
        exaerror.create("E-EDL-7", "Got no results for statement '{{statement}}'", {statement = "statement"}):add_ticket_mitigation()
                :raise()
    end
end
```

Manually adding a line break (e.g. before the table) does not help, lua-format reverts this change.

I also tried setting the `break_before/after_*` options to `true`, but it didn't help.

```yml
# Complete .lua-format:
column_limit: 120
indent_width: 4
use_tab: false
tab_width: 4
continuation_indent_width: 8
spaces_before_call: 1
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
align_args: true
break_after_functioncall_lp: false
break_before_functioncall_rp: false
spaces_inside_functioncall_parens: false
spaces_inside_functiondef_parens: false
align_parameter: true
chop_down_parameter: false
break_after_functiondef_lp: false
break_before_functiondef_rp: false
align_table_field: true
break_after_table_lb: true
break_before_table_rb: true
chop_down_table: false
chop_down_kv_table: true
table_sep: ","
column_table_limit: 120
extra_sep_at_table_end: false
spaces_inside_table_braces: false
break_after_operator: true
double_quote_to_single_quote: false
single_quote_to_double_quote: false
spaces_around_equals_in_field: true
line_breaks_after_function_body: 1
line_separator: input
```
