### ISSUE TITLE
[Question/Feature Request]: `chop_down_parameter` and `align_parameter`

### ISSUE THREAD

**Issue by lmburns** [Koihik/LuaFormatter#247]
<details>
<Summary>Configuration</summary>

```yaml
column_limit: 90
indent_width: 2
use_tab: false
tab_width: 4
continuation_indent_width: 4
keep_simple_control_block_one_line: false
keep_simple_function_one_line: false
align_args: true
align_parameter: false
align_table_field: true
spaces_before_call: 1
spaces_inside_functioncall_parens: false
spaces_inside_functiondef_parens: false
spaces_inside_table_braces: true
spaces_around_equals_in_field: true
chop_down_parameter: true
chop_down_table: true
chop_down_kv_table: true
break_after_functioncall_lp: true
break_before_functioncall_rp: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
break_after_table_lb: true
break_before_table_rb: true
break_after_operator: true
table_sep: ","
extra_sep_at_table_end: true
double_quote_to_single_quote: false
single_quote_to_double_quote: true
line_breaks_after_function_body: 1

column_table_limit: 80
line_separator: lf
```

</details>

If I have something like the following:

```lua
map(
    "t", self.cfg.layout_mapping, function()
      api.nvim_win_set_config(
          self.winid, M.get_view(self.cfg.views[g.__lf_layout_idx])
      )
      g.__lf_layout_idx = g.__lf_layout_idx < #self.cfg.views and g.__lf_layout_idx +
                              1 or 1
    end
)
```

How could I get it to break each parameter onto its own line (similar to something like `rustfmt`)
I've tried modifying several configuration options but could not get it to work. I thought
the most relevant options here would be `chop_down_parameter` and `align_parameter`, but they don't
do what I was expecting.

Maybe another option could be given to the configuration?

```lua
map(
    "t",
    self.cfg.layout_mapping,
    function()
      api.nvim_win_set_config(
          self.winid, M.get_view(self.cfg.views[g.__lf_layout_idx])
      )
      g.__lf_layout_idx = g.__lf_layout_idx < #self.cfg.views and g.__lf_layout_idx +
                              1 or 1
    end
)
```

For instance [`lua-fmt`](https://github.com/trixnz/lua-fmt) does this to the function call:

```lua
map(
    "t",
    self.cfg.layout_mapping,
    function()
        api.nvim_win_set_config(self.winid, M.get_view(self.cfg.views[g.__lf_layout_idx]))
        g.__lf_layout_idx = g.__lf_layout_idx < #self.cfg.views and g.__lf_layout_idx + 1 or 1
    end
)
```

---

On a side note, I see the [Chop down operators #205](https://github.com/Koihik/LuaFormatter/issues/205) issue, which would make the call look even nicer

<details>
<Summary>Like</summary>

```lua
map(
    "t",
    self.cfg.layout_mapping,
    function()
      api.nvim_win_set_config(
          self.winid, M.get_view(self.cfg.views[g.__lf_layout_idx])
      )
      g.__lf_layout_idx = g.__lf_layout_idx < #self.cfg.views
                              and g.__lf_layout_idx + 1
                              or 1
    end
)
```

</details>
