### ISSUE TITLE
If statement wrapped up

### ISSUE THREAD

**Issue by hinell** [Koihik/LuaFormatter#288]
```lua
self.xyz = {
{
	description = "...",
	function()
		if #vim.lsp.get_active_clients() > 0 then
			vim.lsp.buf.hover()
		end
	end
}
```
```lua
self.xyz = {
{
	description = "...",
	function()
		if #vim.lsp.get_active_clients() > 0 then vim.lsp.buf.hover() end
	end
}
```
I'm getting the above `if ... then ... end` statement constantly wrapped up despite limit for 80 columns. 

Please, make it possible to keep it wrapped. Thanks!

### Config

```yml
column_limit                      : 80
indent_width                      : 1
use_tab                           : true
tab_width                         : 4
continuation_indent_width         : 1
spaces_before_call                : 1

# ... the rest is default
```
